FROM quay.io/ansiblegalaxy/galaxy-base:latest

# Install node.js and yarn
RUN dnf -y install --setopt=tsflags=nodocs nodejs rsync \
    && curl -sL -o '/etc/yum.repos.d/yarn.repo' 'https://dl.yarnpkg.com/rpm/yarn.repo' \
    && dnf -y install --setopt=tsflags=nodocs yarn \
    && dnf -y clean all \
    && rm -rf /var/cache/yum

RUN mkdir -p /galaxy
COPY . /galaxy
WORKDIR /galaxy

RUN /galaxy/scripts/docker/release/build.sh
